### ISSUE TITLE
ConsenSys/uport-proxy or uport-project/uport-proxy ?

### ISSUE THREAD

**Issue by harlantwood** [uport-project/uport-proxy#2]
It's confusing to have both:

https://github.com/uport-project/uport-proxy
and
https://github.com/ConsenSys/uport-proxy

with no clear indication of which should be preferred.

Maybe a note at the top of one readme pointing to the other as the master copy? Or if these are divergent projects, maybe summarize how/why they are different?

**Comment by harlantwood** [comment]
made an issue there too: https://github.com/ConsenSys/uport-proxy/issues/25

**Comment by ajunge** [comment]
This is the right one. Sorry for the confusion
